# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-17 14:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0002_remove_stay_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journey',
            name='end',
        ),
        migrations.AddField(
            model_name='journey',
            name='end',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='map.Location'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='journey',
            name='start',
        ),
        migrations.AddField(
            model_name='journey',
            name='start',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='start', to='map.Location'),
            preserve_default=False,
        ),
    ]
