# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-18 21:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0006_auto_20170418_1932'),
    ]

    operations = [
        migrations.AddField(
            model_name='journey',
            name='route_id',
            field=models.CharField(default='', max_length=40),
        ),
    ]
