# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-01-02 10:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(default='', max_length=50)),
                ('link', models.URLField()),
                ('cost', models.FloatField()),
                ('datetime', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Journey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.CharField(default='', max_length=50)),
                ('end', models.CharField(default='', max_length=50)),
                ('datetime', models.DateTimeField()),
                ('route_info', models.CharField(default='{}', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Stay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(default='', max_length=50)),
                ('datetime', models.DateTimeField()),
                ('duration', models.DurationField()),
                ('link', models.URLField(default='https://airbnb.co.uk')),
            ],
        ),
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('color', models.CharField(max_length=6)),
            ],
        ),
        migrations.AddField(
            model_name='journey',
            name='method',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='map.Transport'),
        ),
    ]
