# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2019-01-03 23:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('link', models.URLField()),
                ('cost', models.FloatField()),
                ('day', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Journey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.CharField(default='', max_length=50)),
                ('end', models.CharField(default='', max_length=50)),
                ('day', models.IntegerField()),
                ('route_info', models.CharField(default='{}', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Stay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('day', models.IntegerField()),
                ('end_day', models.IntegerField()),
                ('link', models.URLField(default='https://airbnb.co.uk')),
            ],
        ),
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('color', models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(default='USA', max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
        migrations.AddField(
            model_name='stay',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='map.Trip'),
        ),
        migrations.AddField(
            model_name='journey',
            name='method',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='map.Transport'),
        ),
        migrations.AddField(
            model_name='journey',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='map.Trip'),
        ),
        migrations.AddField(
            model_name='activity',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='map.Trip'),
        ),
    ]
