# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-17 12:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import geoposition.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Journey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('duration', models.DurationField()),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('position', geoposition.fields.GeopositionField(max_length=42)),
            ],
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('location_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='map.Location')),
                ('link', models.URLField()),
                ('cost', models.FloatField()),
                ('date', models.DateField()),
            ],
            bases=('map.location',),
        ),
        migrations.CreateModel(
            name='Stay',
            fields=[
                ('location_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='map.Location')),
                ('checkin', models.DateTimeField()),
                ('duration', models.DurationField()),
                ('address', models.CharField(max_length=100)),
            ],
            bases=('map.location',),
        ),
        migrations.AddField(
            model_name='journey',
            name='end',
            field=models.ManyToManyField(related_name='end', to='map.Location'),
        ),
        migrations.AddField(
            model_name='journey',
            name='start',
            field=models.ManyToManyField(related_name='start', to='map.Location'),
        ),
    ]
