# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-01-03 00:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stay',
            name='location',
        ),
        migrations.AddField(
            model_name='stay',
            name='lat',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stay',
            name='lng',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
