# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2019-01-04 00:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='map.Trip'),
        ),
        migrations.AlterField(
            model_name='journey',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journeys', to='map.Trip'),
        ),
        migrations.AlterField(
            model_name='stay',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stays', to='map.Trip'),
        ),
    ]
