# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-17 15:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0003_auto_20170417_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='journey',
            name='method',
            field=models.CharField(default='train', max_length=40),
            preserve_default=False,
        ),
    ]
