# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-18 19:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0005_auto_20170418_1929'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='date',
            new_name='datetime',
        ),
        migrations.RenameField(
            model_name='journey',
            old_name='checkin',
            new_name='datetime',
        ),
        migrations.RenameField(
            model_name='stay',
            old_name='checkin',
            new_name='datetime',
        ),
    ]
