# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-30 10:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0007_journey_route_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='journey',
            name='route_name',
            field=models.CharField(default='', max_length=40),
        ),
    ]
