# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-02-11 23:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0010_auto_20180211_2238'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transport',
            name='name',
        ),
    ]
