# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-02-11 23:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0011_remove_transport_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='transport',
            name='name',
            field=models.CharField(default='train', max_length=20),
            preserve_default=False,
        ),
    ]
