# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-01-02 00:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0012_transport_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='location_ptr',
        ),
        migrations.RemoveField(
            model_name='journey',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='journey',
            name='price',
        ),
        migrations.RemoveField(
            model_name='journey',
            name='route_id',
        ),
        migrations.RemoveField(
            model_name='journey',
            name='route_name',
        ),
        migrations.RemoveField(
            model_name='stay',
            name='location_ptr',
        ),
        migrations.AddField(
            model_name='activity',
            name='id',
            field=models.AutoField(auto_created=True, default=-1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='activity',
            name='location',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='journey',
            name='route_info',
            field=models.CharField(default='{}', max_length=200),
        ),
        migrations.AddField(
            model_name='stay',
            name='id',
            field=models.AutoField(auto_created=True, default=-1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stay',
            name='location',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='journey',
            name='end',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='journey',
            name='start',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.DeleteModel(
            name='Location',
        ),
    ]
